extends:
- standard
- plugin:react/recommended
- prettier
- prettier/react
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    impliedStrict: true
    classes: true
env:
  browser: true
  node: true
  jest: true
rules:
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".js"
    - ".jsx"
  react/prop-types: 0
  no-unused-vars:
  - error
  - vars: local
    args: none
  prettier/prettier:
  - error
  - semi: false
    singleQuote: true
    printWidth: 120
plugins:
- prettier
